### PR TITLE
Redesign Footer Section

### PR DESCRIPTION
**Pull request by YakeDev**
- Added social media icons with hover effects.
- Made the footer sticky at the bottom of the page.
- Improved typography and layout for better readability.

image

### CODE REVIEW

**Comment by manoj9896** [comment]
@Ctoic 
This pull request contains wrong changes for the `pbd.html`. You should revert it.

**Comment by manoj9896** [comment]
@YakeDev can you update this file to it actual content

**Comment by YakeDev** [comment]
@manoj9896 
Sure

**Comment by Ctoic** [comment]
Exactly @YakeDev thanks for pointing out @manoj9896

**Pull request merged**
