### PR TITLE
feat: Made home page responsive

### PR DESCRIPTION
**Pull request by imrehankhan**
Solved issue #152 
Made the home page responsive. Working fine on mobile phones and tablets

Screenshot 2024-12-14 at 10 29 53 PM

### CODE REVIEW

**Comment by Ctoic** [comment]
You have Included only one audio files can you add the remaining files /.

**Comment by imrehankhan** [comment]
@Ctoic I have added all audio files

**Comment by Ctoic** [comment]
Still not eorking. You are not following the theme.

**Comment by Ctoic** [comment]
I'm closing your pull request @imrehankhan always remember contribute quality code to a project.

**Pull request closed without merging**
