### PR TITLE
Feature Added: User feedback form submission via email 

### PR DESCRIPTION
**Pull request by AdityaJ2305**
Fix: #58 
- Added User Feedback Submission using emailJS 

Here is the template for Email which need to put in emailJs account :
>Subject: New Feedback Submission

> Hello Team,
> 
> A new feedback form has been submitted with the following details:
> 
> Name: {{name}}
> Email: {{email}}
> Feedback: {{feedback}}
> 
> This feedback was submitted via the app's feedback form.
> 
> Best regards,
> Your App's Feedback System

Template id:  `feedback_form`

Refer to setup emailJs account: [Account Setup Doc](https://www.emailjs.com/docs/tutorial/overview/)

### CODE REVIEW

**Comment by Ctoic** [comment]
Resolve conflict @AdityaJ2305

**Comment by AdityaJ2305** [comment]
> Resolve conflict @AdityaJ2305

@Ctoic  Done

**Comment by Ctoic** [comment]
lisbook.netlify.app here is the current version of app, dear I haven't got time to rest from morning can you review your code. here is the latest version check if it works after you add your code

**Comment by Ctoic** [comment]
@AdityaJ2305

**Comment by Ctoic** [comment]
Always fetch the latest changes from the remote branch before you push your code @AdityaJ2305

**Comment by AdityaJ2305** [comment]
> Always fetch the latest changes from the remote branch before you push your code @AdityaJ2305

I’ll ensure it doesn’t happen again.

**Comment by AdityaJ2305** [comment]
> lisbook.netlify.app here is the current version of app, dear I haven't got time to rest from morning can you review your code. here is the latest version check if it works after you add your code

@Ctoic, please fill in your EmailJS credentials to get it working. I tested it with my personal account, and it works perfectly.

**Comment by AdityaJ2305** [comment]
Hey @Ctoic , any update ?

**Comment by Ctoic** [comment]
@AdityaJ2305 I'm on it.

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 I'm on it.

ok, Let me know if any changes required

**Comment by YakeDev** [comment]
@AdityaJ2305 
Can you add this form in CONTACT Page?

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 Can you add this form in CONTACT Page?

sure

**Comment by AdityaJ2305** [comment]
@Ctoic Changes merged with the latest main repo, conflicts resolved, and tested successfully.

**Pull request merged**
