### PR TITLE
Add loading animation while page loads

### PR DESCRIPTION
**Pull request by 2MJ-DEV**
- Implemented a Bootstrap 5.3.3 spinner to indicate page loading status.
    - Customized the spinner color to match the requested #1db954 (green).  
    - Centered the spinner on the screen with a semi-transparent background.
    - Added functionality to hide the spinner once the page is fully loaded using JavaScript.

### CODE REVIEW

**Comment by 2MJ-DEV** [comment]
Screenshot_20241014_202927

**Comment by Ctoic** [comment]
Check in the deployment link @2MJ-DEV it is not showing any screen but just the loading icon.

**Comment by 2MJ-DEV** [comment]
@Ctoic Yet, everything is normal for me!!

**Comment by Ctoic** [comment]
Yes I'm mergin it now @2MJ-DEV it's working fine now

**Comment by 2MJ-DEV** [comment]
All right

**Pull request merged**
