### PR TITLE
Added Tooltips on hover. Added action button color change on hover.

### PR DESCRIPTION
**Pull request by AdityaBavadekar**
image

### CODE REVIEW

**Comment by AdityaBavadekar** [comment]
Fixes #40

**Comment by AdityaBavadekar** [comment]
image

**Comment by Ctoic** [comment]
Hey  @AdityaBavadekar you have implemented really well for desktop but when I checked it for mobile application it is not that much responsive. All the books above the current book are listed and there is no responsiveness. If you want to merge this and work on next issue i will merge this and assign you new issue. Or make it responsive for mobile as well then i will merge it.

**Comment by AdityaBavadekar** [comment]
I will try to make it responsive.

**Comment by Ctoic** [comment]
Sure @AdityaBavadekar Best of luck. If you need any help feel free to ask.

**Comment by AdityaBavadekar** [comment]
Hello @Ctoic , I have tried to make it more responsive.

https://github.com/user-attachments/assets/79ffa45f-21d7-4748-b687-f6353ee163a7

**Comment by Ctoic** [comment]
I will upload the audiobook for the above books you addedd in faviorite will you add them accordingly to the page ?I will merge this as well but in my opinion the faviorite books should be placed below currently playing book. what do you think ?

**Comment by Ctoic** [comment]
It looks good on mobile as well. Well done @AdityaBavadekar I'm mergin it. Happy coding 😄

**Comment by AdityaBavadekar** [comment]
> I will upload the audiobook for the above books you addedd in faviorite will you add them accordingly to the page ?I will merge this as well but in my opinion the faviorite books should be placed below currently playing book. what do you think ?

The books shows as a list are "Top Audio Books" (for eg: 300+ users have chosen to listen to these books). I have not added the part for listing favourite books, in that case their ids would have to be stored locally.

**Comment by Ctoic** [comment]
Can we add the audio files of these books in current page ? if so i can create a new issue and assign it to you.

**Comment by AdityaBavadekar** [comment]
Yes. What I have currently done is created a books.json which has data about all books in the list. Audio files can be added in audio_files part.
```
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "published_year": 1960,
        "genre": "Fiction",
        "audio_files": {
            "chapter1": "audio/mockingbird_ch1.mp3",
            "chapter2": "audio/mockingbird_ch2.mp3"
        }
    }
```

And this can be also modified to use this format for each audio file:
```
      {
        "chapter_number": 1,
        "title": "Chapter 1",
        "audio_file": "audio/chapter3.mp3"
      }
```

**Comment by AdityaBavadekar** [comment]
@Ctoic I am interested, you can assign me this issue.

**Comment by Ctoic** [comment]
okay will create an issue and assign it to you get ready @AdityaBavadekar 🚀

**Pull request merged**
