### PR TITLE
Redesigned audio player, added controls and favicon

### PR DESCRIPTION
**Pull request by YakeDev**
- Redesigned the audio player for improved user experience.
- Added control buttons for:
   - Volume up/down
   - Play/Pause
   - Fast forward (+30s) and rewind (-30s)
- Add a favicon on all pages

### CODE REVIEW

**Comment by Ctoic** [comment]
Hey @YakeDev Perfect 💯

**Comment by YakeDev** [comment]
> Hey @YakeDev Perfect 💯

Hey @Ctoic Thank You

**Comment by Ctoic** [comment]
Are you free ?

**Comment by Ctoic** [comment]
@YakeDev

**Comment by YakeDev** [comment]
Why this button ?

image

**Comment by YakeDev** [comment]
> Are you free ?

Yes

**Comment by Ctoic** [comment]
We can talk for further enhancement of project and overall I'm so impressed with your work. We will collab in future as well @YakeDev

**Comment by Ctoic** [comment]
That button is for sharing the progress with friends

**Comment by Ctoic** [comment]
I wanted more people to colloborate because it is hacktoberfest even the new comers so I accepted it we can fix it later.

**Comment by YakeDev** [comment]
> I wanted more people to colloborate because it is hacktoberfest even the new comers so I accepted it we can fix it later.

Ah ok, Good

**Comment by YakeDev** [comment]
> We can talk for further enhancement of project and overall I'm so impressed with your work. We will collab in future as well @YakeDev

It will be a pleasure to collaborate with you, as it will help me improve, especially since I'm still learning and just starting out.

**Pull request merged**
