### PR TITLE
Improved theme management and updated interface

### PR DESCRIPTION
**Pull request by YakeDev**
- Added dynamic background color management for `playlist-card` elements depending on theme (light or dark).
- CSS updated to support `light-theme` and `dark-theme` classes, ensuring smooth color transition when changing theme.
- Corrected theme-toggle behavior to ensure a consistent experience across the page.
- Harmonization of text and background colors in both themes.

Objective: Improve UX by ensuring that all page elements react correctly to theme changes and by harmonizing the user interface.

### CODE REVIEW

**Comment by Ctoic** [comment]
Reviewing your code @YakeDev

**Comment by Ctoic** [comment]
Hey also change the description of the books. Can we do it dynamically ?

**Comment by YakeDev** [comment]
> Can we do it dynamically ?

Yes, absolutely! Could you clarify what you mean by "dynamically"? I'd appreciate more details so I can better understand your expectations and provide the most appropriate solution.

**Comment by Ctoic** [comment]
I mean using openai's api to create descriptions for the books ? or anyother way when we add a book the description should be add automatically.

**Comment by YakeDev** [comment]
> I mean using openai's api to create descriptions for the books ? or anyother way when we add a book the description should be add automatically.

Do you mean every book should have different description?

**Comment by Ctoic** [comment]
Yes Exactly. One way is we write it by ourself but if we can use some genai if possible then it will be a cool feature

**Comment by YakeDev** [comment]
> Yes Exactly. One way is we write it by ourself but if we can use some genai if possible then it will be a cool feature

Okay, will do

**Pull request merged**
