### PR TITLE
Add reading page and dynamic book details display

### PR DESCRIPTION
**Pull request by YakeDev**
- Added reading.html to display metadata of the selected book
- Introduced reading.js to manage the display of book details
- Implemented a function in script.js to show books as cards on the test page
- **Note :** _Clicking on book chapters currently does not initiate playback_

image

### CODE REVIEW

**Comment by YakeDev** [comment]
@Ctoic please, can you check, **(the chapters doesn't play)**

here is the link
https://deploy-preview-128--lisbook.netlify.app/test.html

**Comment by thilakjo** [comment]
Ur html files need to have cursor, they are missing. 

Make sure to copy header and footer from index.html when u create new one or else some parts will fail.

Nice efforts

**Comment by YakeDev** [comment]
> Ur html files need to have cursor, they are missing.
> 
> Make sure to copy header and footer from index.html when u create new one or else some parts will fail.
> 
> Nice efforts

The problem of cursor, it is not from me,

**Comment by YakeDev** [comment]
Hey @Ctoic 

**Enhance code structure and book management**

- Refactored the code into ES6 modules, allowing for better organization and reusability of functionalities.
- Most features are now encapsulated in modules, making maintenance and testing easier.
- Integrated a `books.json` file to dynamically add all books.
- Created the `reading.html` page to display book metadata dynamically.
- Developed the `reading.js` file to manage the logic for the `reading.html` page.

_**However, a bug persists: the chapter progress bar is not functioning correctly. I have not yet identified the source of the issue and will continue investigating.**_

**Comment by YakeDev** [comment]
> Hey @Ctoic
> 
> **Enhance code structure and book management**
> 
> * Refactored the code into ES6 modules, allowing for better organization and reusability of functionalities.
> * Most features are now encapsulated in modules, making maintenance and testing easier.
> * Integrated a `books.json` file to dynamically add all books.
> * Created the `reading.html` page to display book metadata dynamically.
> * Developed the `reading.js` file to manage the logic for the `reading.html` page.
> 
> _**However, a bug persists: the chapter progress bar is not functioning correctly. I have not yet identified the source of the issue and will continue investigating.**_

Hello @Ctoic,
Could you please help me review and address this bug if possible? I'm available to discuss any questions you might have.

Thank you!

**Comment by YakeDev** [comment]
> Ur html files need to have cursor, they are missing.
> 
> Make sure to copy header and footer from index.html when u create new one or else some parts will fail.
> 
> Nice efforts

Thank you,

**Comment by Ctoic** [comment]
> > Ur html files need to have cursor, they are missing.
> > Make sure to copy header and footer from index.html when u create new one or else some parts will fail.
> > Nice efforts
> 
> The problem of cursor, it is not from me,

Exactly I had merge code which is causing the issue. It's not because of your changes @YakeDev

**Comment by YakeDev** [comment]
in My last PR I corrected all problem
@Ctoic

**Comment by YakeDev** [comment]
> @Ctoic please, can you check, **(the chapters doesn't play)**
> 
> here is the link https://deploy-preview-128--lisbook.netlify.app/

**Comment by Ctoic** [comment]
You had and now are you working on any specific issue @YakeDev ?

**Comment by YakeDev** [comment]
> You had and now are you working on any specific issue @YakeDev ?

I was waiting your comment about this issue, @Ctoic

**Comment by YakeDev** [comment]
I close it by mistake, can you reopen it please? @Ctoic

**Comment by Ctoic** [comment]
The branch have conflicts which needs to be resolved before merging it @YakeDev

**Comment by YakeDev** [comment]
> The branch have conflicts which needs to be resolved before merging it @YakeDev

I didn't found how to do it

**Comment by YakeDev** [comment]
> The branch have conflicts which needs to be resolved before merging it @YakeDev

image

@Ctoic

**Pull request closed without merging**
