### PR TITLE
Added Download button to all podcast

### PR DESCRIPTION
**Pull request by IngaleChinmay04**
Added download button for all podcast in all files

for the issue: #33 

https://github.com/user-attachments/assets/b6dcce06-2daf-40d9-8ae5-dc65545ff128

### CODE REVIEW

**Comment by Ctoic** [comment]
So far so good @IngaleChinmay04 can you just update the download icon.

**Comment by IngaleChinmay04** [comment]
image
will this one work?

**Comment by Ctoic** [comment]
Yes sure

**Comment by YakeDev** [comment]
I was thinking Green instead red

**Pull request merged**
