### PR TITLE
changed the ui of the navbar

### PR DESCRIPTION
**Pull request by Suvendu-UI**

### CODE REVIEW

**Comment by YakeDev** [comment]
Hey @Suvendu-UI 
Can you add screenshot please?

**Comment by Suvendu-UI** [comment]
ya sure 

https://github.com/user-attachments/assets/0df5bfe1-55af-40a8-93d1-752a59be468e

**Comment by Suvendu-UI** [comment]
hey @YakeDev can you review this

**Comment by YakeDev** [comment]
> https://deploy-preview-103--lisbook.netlify.app

the loader is not on middle

image

**Comment by YakeDev** [comment]
> hey @YakeDev can you review this

The navbar doesn't appear as expected. Please refer to the screenshot I’ve provided. Could you kindly review and correct it?

image

**Comment by Suvendu-UI** [comment]
> > hey @YakeDev can you review this
> 
> The navbar doesn't appear as expected. Please refer to the screenshot I’ve provided. Could you kindly review and correct it?
> 
> image

my objective was to create space in the navbar and improve the ui

**Comment by YakeDev** [comment]
> > > hey @YakeDev can you review this
> > 
> > 
> > The navbar doesn't appear as expected. Please refer to the screenshot I’ve provided. Could you kindly review and correct it?
> > image
> 
> my objective was to create space in the navbar and improve the ui
Do you review it?

**Pull request closed without merging**
