### PR TITLE
Aded a loading animation while page is loading

### PR DESCRIPTION
**Pull request by 2MJ-DEV**
- Added a 1-second delay before hiding the loader animation
- Ensured the loader is visible even on fast-loading pages
- Updated JavaScript logic to improve overall page load experience

### CODE REVIEW

**Comment by Ctoic** [comment]
@2MJ-DEV  hey we are working on overall design of the app right now I cannot merge hyour request. Stay tuned will open the issue again

**Comment by 2MJ-DEV** [comment]
@Ctoic _I agree, because some codes change - everything._

**Comment by Ctoic** [comment]
Now the basic design is ready we will not change it so you can work on it again @2MJ-DEV Thanks for your time and dedication ❤️

**Comment by 2MJ-DEV** [comment]
Thank you! I'm off

**Comment by Ctoic** [comment]
Okay sure so I will close the issue and assign it to someone else thanks for your time @2MJ-DEV

**Comment by 2MJ-DEV** [comment]
I said I'm working on it

**Comment by Ctoic** [comment]
Okay sure @2MJ-DEV sorry for the inconvinience.

**Comment by Ctoic** [comment]
Go ahead 👍🏼

**Comment by 2MJ-DEV** [comment]
Thank you very much, I will try not to modify the rest of the code

**Comment by Ctoic** [comment]
Sure If you need beginer's friendly issue create one I will assign it to you.

**Comment by 2MJ-DEV** [comment]
great @Ctoic  I will do it

**Pull request closed without merging**
