### PR TITLE
Added working for inserting, saving and rendering Favourite books list

### LINKED ISSUE #52: Adding audio books to the faviorite section.

### PR DESCRIPTION
**Pull request by AdityaBavadekar**
The favourite book ids are stored locally, so even after refresh the list remains the same.

https://github.com/user-attachments/assets/be2a9001-551c-42ec-8b25-bc4ce99cde55

Fixes #52

### CODE REVIEW

**Comment by Ctoic** [comment]
You are doing great @AdityaBavadekar

**Comment by Ctoic** [comment]
Can you resolve the conflicts and push the code @AdityaBavadekar

**Comment by AdityaBavadekar** [comment]
Sure

**Comment by AdityaBavadekar** [comment]
I have resolved the conflicts.

**Pull request merged**
