### PR TITLE
file structure inproved for Lisbook [#10]

### PR DESCRIPTION
**Pull request by VaradJadhav**

### CODE REVIEW

**Comment by Ctoic** [comment]
okay great you have worked really hard. We are reviewing your code. Did you checked weather the live application runs after the files are sorted ?

**Comment by VaradJadhav** [comment]
Yes i have checked, application is working fine.

**Comment by VaradJadhav** [comment]
Hey can you merge it quickly, so that i can go with other issues with updated file structure?

**Comment by Ctoic** [comment]
After changing file structure it is not running. Kindly review your changes

**Pull request closed without merging**
